### ISSUE TITLE
Auto-lock onto speaker

### ISSUE THREAD

**Issue by NolanCampbell2357** [frc2357/FRC-2024#28]
As the driver I want to be able to press the rotation stick down to lock the robot's rotation to forward-facing the speaker, so it is easier to score.

**Comment by Tyson453** [comment]
@NolanCampbell2357 My vision for this was that whenever the driver holds the right trigger down half way, it starts getting the shooter up to speed, tracking the april tag and updating the robot rotation and pivot angle repeatedly until the driver fully pulls the right trigger, after which the robot stops moving (regardless if the driver is trying to or not) and locks the wheels. Then the intake runs the note into the shooter and we score. The taking full control of the driving isn't crucial but it would guarantee that the driver isn't trying to move while shooting and we don't get knocked off our shot by a defender.
